#pragma once

#include <MessageIdentifiers.h>

enum GameMessages {

	ID_MESSAGE = ID_USER_PACKET_ENUM + 1,
	ID_SERVER_MESSAGE,
	ID_SERVER_SET_CLIENT_CONNECTED,
	ID_SERVER_SET_CLIENT_ID,
	ID_SERVER_SET_CLIENT_CHANNEL,
	ID_SERVER_SET_CLIENT_NAME,
	ID_SERVER_SET_CLIENTLIST_SIZE,
	ID_SERVER_UPDATE_CLIENTLIST,
	ID_CLIENT_CHAT_MESSAGE_BROADCAST,
	ID_CLIENT_CHAT_MESSAGE_WHISPER,
	ID_CLIENT_VOICE_MESSAGE,
	ID_CLIENT_REQUEST_CHANNEL_CHANGE,
	ID_CLIENT_REQUEST_DISCONNECTION,
	ID_CLIENT_REQUEST_NAME_CHANGE
};

enum MessageChannelType {

	ALL_CLIENTS,
	TEAM_ONLY,
	WHISPER
};

struct ClientInfo {

	RakNet::RakNetGUID GUID;
	int ID = 0;
	int Channel = 0;
	std::string ProfileName = "PROFILE NAME NOT SET";
};